[project]
name = "mock-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
    "jinja2>=3.1.0",
    "python-multipart>=0.0.5",
]
